spring.application.name=11_MAO_MEANMEAN_SR_SPRING_Homework003
spring.datasource.url=jdbc:postgresql://localhost:5432/exception_handling
spring.datasource.username=postgres
spring.datasource.password=A001$
spring.jackson.default-property-inclusion=non_null